version: '3.4'

services:
  integrationtesting.api:
    image: integrationtestingapi
    build:
      context: .
      dockerfile: IntegrationTesting.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "52101:80"
      - "52102:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - sqlserver
    networks:
      - integrationtestingapi-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=AdminSqlServer10
      - MSSQL_PID=Express
    ports:
      - "14800:1433"
    networks:
      - integrationtestingapi-network

networks:
  integrationtestingapi-network:
    driver: bridge